using OpenEdge.helper;

namespace OpenEdge.vocab;

internal class TagTease : BaseVocab
{
	public TagTease(Voc voc)
		: base(voc)
	{
		tagTeases = new string[162][]
		{
			new string[1] { "Femboy" },
			new string[3] { "I love femboys, few people know their place as well as them", "don't you long to be in that cute femboys place?", "I love watching the slow development as men become more and more feminine" },
			new string[2] { "Girl(s)", "Fully-Clothed" },
			new string[2] { "just look at that form", "nothing can hide that beautiful body" },
			new string[1] { "Futa(s)" },
			new string[2] { "Futa's get to enjoy the best of both worlds", "who wouldn't be jealous of a body like that?" },
			new string[3] { "Nude", "!Cock", "Solo" },
			new string[1] { "do you deserve to see something so delicate?" },
			new string[1] { "Suggestive" },
			new string[2] { "maybe you can see something if you look extra hard", "they're not even nude, but still you'll stroke like there is no tomorrow" },
			new string[1] { "Fully-Clothed" },
			new string[2] { "you can't even see anything anymore", "what exactly are you stroking to?" },
			new string[1] { "Censored" },
			new string[3] { "if you don't want me to censor this even further, I'd recommend good behavior", "you really love censors don't you?", "you're such a good @boy, for denying yourself even the porn you love" },
			new string[1] { "Solo" },
			new string[3] { "they're gorgeous", "they're attractive", "what I wouldn't give to have some fun with them" },
			new string[1] { "Duo" },
			new string[2] { "they look like they're having fun together", "you'd just get in the way, so stay here and stroke" },
			new string[1] { "Threesome" },
			new string[1] { "do you still dream about taking part in a threesome?" },
			new string[1] { "Group" },
			new string[2] { "I've heard that orgies are amazing", "just imagine the smell in that room" },
			new string[1] { "Caption" },
			new string[1] { "you're even getting ridiculed by the porn you love" },
			new string[1] { "Femdom" },
			new string[1] { "it's so erotic watching a dominant woman" },
			new string[1] { "Maledom" },
			new string[3] { "some men deserve to take what they desire", "just look at those well shaped muscles", "men like that can just take what they want" },
			new string[1] { "Masturbation" },
			new string[1] { "it's hot watching someone else masturbate isn't it? I would know" },
			new string[2] { "Vanilla", "!virgin" },
			new string[1] { "you can give up on pussy from now on" },
			new string[1] { "Anal" },
			new string[2] { "they're really impressive for taking it that deep", "just the thought of having to train yourself sexually makes anal such a hot concept to me" },
			new string[1] { "Cunnilingus" },
			new string[2] { "getting serviced like that feels amazing", "I'm getting wet just looking at them" },
			new string[1] { "Double Penetration" },
			new string[3] { "god that would feel amazing", "don't try to compete with men like these, they take what they want", "a couple rounds like that and even the most stuck-up bitch will submit" },
			new string[1] { "Thighjob" },
			new string[2] { "how good must it feel to ram your @cock in between those legs", "why do you look so hot and bothered? they're not even having sex" },
			new string[1] { "Footjob" },
			new string[2] { "now this is a way I would consider pleasuring you if you've been extra good", "some people may call your fascination with feet weird, but I think it's natural for a @man like you" },
			new string[2] { "Handjob", "POV" },
			new string[4] { "even in your fantasy's you're just longing for a handjob", "can't you dream bigger than a handjob?", "even a simple handjob is too much for a @man like you", "you would have burst as soon as that hand wrapped around your @cock" },
			new string[1] { "Blowjob" },
			new string[2] { "just imagine that soft tongue running down your length", "keep dreaming @subTitle you're not getting a blowjob any time soon" },
			new string[2] { "Boobjob", "POV" },
			new string[2] { "don't expect this to happen to you", "I'm not sure that you could pull this off as well" },
			new string[1] { "Boobs" },
			new string[2] { "you love staring at breasts for hours on end don't you?", "tits must be a divine creation, there is simply no chance of such beauty happening by chance" },
			new string[1] { "Ass" },
			new string[2] { "that's such a nice ass", "I'd kill for an ass like that" },
			new string[1] { "Mouth" },
			new string[3] { "you're not imagining putting your @cock in that mouth are you? it's never going to happen", "just imagine that warm mouth sucking you off", "doesn't that mouth look so inviting?" },
			new string[2] { "Cock", "Maledom" },
			new string[2] { "I want you to compare that dick to your own @cock", "so this is what they mean by 'penis awe'" },
			new string[2] { "Feet", "humiliation" },
			new string[6] { "how fitting, a loser like you ought to like feet", "you really have given up on pussy haven't you?", "even my toes are too much for you to handle", "you love pretty little feet don't you?", "you should let people know that you're into feet, so they can avoid wearing shoes that are too revealing around you", "you're just a pathetic little foot-lover aren't you" },
			new string[1] { "Hands" },
			new string[4] { "imagine getting off to just a hand", "what exactly is attractive to you about hands?", "can you imagine a hand like that slowly stroking your @cock", "how good would a handjob feel from hands like those" },
			new string[1] { "Pussy" },
			new string[1] { "spread or not, pussy's always look like they're just begging to get filled" },
			new string[1] { "Thighs" },
			new string[3] { "thick thighs save lives", "those thighs look so soft and inviting", "you'd be happy just sticking your @cock in between those puffy thighs wouldn't you?" },
			new string[1] { "Midriff" },
			new string[2] { "a cute tummy like that is just to die for isn't it?", "how quickly would you cum if they'd let you rub against their tummy" },
			new string[2] { "Cum", "cei" },
			new string[4] { "just look at that delicious cum trickling down", "is that trickle of cum making you hungry?", "too bad you can't taste that delicious cum", "I don't like the taste of cum, but there is something so hot about lapping it up like a good bitch" },
			new string[1] { "Dildo" },
			new string[1] { "dildo's are so pretty aren't they" },
			new string[1] { "Plug" },
			new string[1] { "that cute hole is plugged up so nice" },
			new string[2] { "Strap-on", "anal" },
			new string[2] { "I'd love to fuck your brains out with a strap-on like that", "few inventions are as depraved as the strap-on, I love it" },
			new string[4] { "Girl(s)", "Group", "!Guy(s)", "!Fully-Clothed" },
			new string[2] { "do you deserve to see these goddesses enjoying themselves?", "few things are as beautiful as lesbians enjoying each other" },
			new string[2] { "Dildo", "anal" },
			new string[3] { "is your ass begging for a pounding?", "just imagine that dildo sliding up your ass", "would you be able to take that dildo as well as them?" },
			new string[2] { "Plug", "plug" },
			new string[1] { "who's plug is bigger, yours or theirs?" },
			new string[2] { "Plug", "@plug" },
			new string[2] { "it looks like you're not the only one enjoying a plug", "are you enjoying that plug as much as they are?" },
			new string[3] { "Plug", "@!plug", "plug" },
			new string[4] { "how badly do you need your plug inside of you after seeing this?", "I'm not showing this, just to make you long for your plug, what are you talking about?", "they look like they're having so much fun with that plug, too bad that you can't join them", "SILENTSTOP: okay, now I want to see you plugged PLUGASS" },
			new string[3] { "Collar", "@!collar", "collar" },
			new string[4] { "they get to wear their collar, are you getting jealous?", "if you're good I may let you wear your collar as well", "why are you whimpering like that? Is it because you miss your collar?", "SILENTSTOP: subs really do look better with a collar on COLLAR" },
			new string[2] { "Collar", "@collar" },
			new string[4] { "you're matching, but I think you're wearing that collar better, my cute sub", "so many cute puppy's to choose from! But you just know that you'll always be my first pick", "just imagine yourself in their position, you've even been collared as well", "aren't you happy? you get to stroke to other puppy's just like yourself" },
			new string[4] { "Girl(s)", "Censored", "Solo", "humiliation" },
			new string[4] { "you don't deserve to see a cute girl like this exposing herself", "you're pathetic for choosing to deny yourself with pictures like these", "you don't get to see her cute body anymore", "you were the one who picked the censored version, I'm sure that the girl would have loved to show off for you" },
			new string[2] { "Censored", "humiliation" },
			new string[1] { "if you don't mind censorship, I could just make you censor all your porn" },
			new string[3] { "Cock", "Maledom", "sph" },
			new string[4] { "just look at that cock, how can yours even be compared to that?", "this is how girls expect a cock to look like", "that dick is making my mouth water", "god that's a dick that just demands that I pleasure it" },
			new string[3] { "Cock", "Futa(s)", "sph" },
			new string[4] { "just look at that cock, how can yours even be compared to that?", "this is how girls expect a cock to look like", "that dick is making my mouth water", "god that's a dick that just demands that I pleasure it" },
			new string[1] { "SPH" },
			new string[2] { "can you even call that a dick anymore? it's more like a clit", "what a cute little dick" },
			new string[1] { "CBT" },
			new string[10] { "cocks deserve punishment", "men are so weak", "just a couple hits and this is what a man turns into", "don't those genitals just make you want to hit them?", "SILENTSTOP: I'm sure you're jealous of that slave, let me help you with that CBTCOCK:", "SILENTSTOP: now you've gotten me in the mood for a beating CBTBALLS:", "they're so good at taking punishment! you really should be taking notes", "I love those pained expressions", "you should be careful, this may inspire me", "just look at that redness, I'm kind in comparison" },
			new string[1] { "Bondage" },
			new string[1] { "I should bind you up as well" },
			new string[1] { "Chastity" },
			new string[6] { "we should get you a cage as well", "a locked up cock is a good cock", "do you fantasize about chastity?", "I'll lock you up too someday, not yet though", "all you need to control a sub is a tiny cage", "you'd be like putty in my hands if I locked you up" },
			new string[1] { "T&D" },
			new string[6] { "you can just see the frustration", "they're so close to orgasm", "clearly they can take a few extra edges", "how long do you think it'll be before they break down?", "are you jealous of that sub? don't worry I'll make you squirm just like them", "you're going to look just like that when I'm done with you" },
			new string[2] { "POV", "humiliation" },
			new string[3] { "this is what you'd see if you weren't such a loser", "even if you change the point of view, you're not there", "I don't get the point of pov porn, you're stroking your @cock" },
			new string[1] { "POV" },
			new string[2] { "is it easier to imagine yourself in the scene with this pov?", "it's almost like you're really there isn't it?" },
			new string[3] { "Vanilla", "POV", "virgin" },
			new string[3] { "does this help your imagination at all my little virgin?", "does the point of view help with your delusion of actually having sex?", "you're not the one having sex and you never will be" },
			new string[2] { "Vanilla", "virgin" },
			new string[4] { "even a virgin like you has idea's about what a pussy should feel like, too bad you'll never find out", "as long as I own you, you're not even getting close to pussy", "millions of people are having sex as we speak, not you though, not now and not ever", "does it feel good, watching others enjoy something you'll never have?" },
			new string[2] { "Vanilla", "POV" },
			new string[1] { "you're deluding yourself by watching POV porn, that's not you ramming into that cute pussy" },
			new string[2] { "analTraining", "Anal" },
			new string[4] { "Anal is really tough, they must have practiced a lot", "you'll be able to take it up the ass like that with time", "are you scared or excited when you think about getting more pleasure from anal than stroking?", "doesn't that just look amazing, you want to feel like that too right?" },
			new string[3] { "analTraining", "Chastity", "Anal" },
			new string[3] { "I'm a kind @missTitle, so even if your @cock was locked I'd grant you pleasure by whatever means necessary", "you'd love to be in their place wouldn't you?", "if your @cock was locked you'd love anal way more, just look at them" },
			new string[2] { "@anal", "Anal" },
			new string[3] { "I'm sure you know how they feel taking it up the butt", "you can get so much pleasure from your ass", "do you imagine yourself as the bottom or the top?" },
			new string[2] { "dildo", "Dildo" },
			new string[2] { "does your dildo look like theirs?", "even if you can't right now you'll be able to take it as well as them in the future" },
			new string[2] { "Masturbation", "Solo" },
			new string[5] { "the two of you can masturbate together", "I do think you look better stroking your brains out than them", "I think I picked right, even compared to them I love the way you look", "masturbation is wonderful to look at, there is nothing but pure lust", "there's something special about witnessing such a private moment in someone's routine" },
			new string[2] { "Maledom", "humiliation" },
			new string[5] { "don't think for a second that anyone will ever service you like this", "some people belong on their knees, that's just the way of the world", "they look like they're having the time of their lives over there", "just keep stroking while looking at what you'll never get", "can you even imagine how that feels, probably not" },
			new string[2] { "cuck", "Maledom" },
			new string[6] { "I'll be honest, I'm not sure if I could hold myself back if a man like that were to make some moves on me", "I'd kill for a sub like that, although he probably wouldn't stay the sub for long", "you know, I may be a switch after all", "I always thought of myself as a dom, but maybe it's just that I haven't found my master yet", "if you don't want me to leave you, you should stop shoving better alternatives in my face", "I'm sure every day would be filled with so much pleasure, serving a man like that" },
			new string[3] { "cuck", "Maledom", "!Solo" },
			new string[1] { "I kind of want to join in with them, but no, I have to watch you stroke your @cock" },
			new string[3] { "POV", "Blowjob", "humiliation" },
			new string[2] { "it's almost as if you're the one getting your dick sucked with pov porn", "don't forget that it's not you getting their dick sucked" },
			new string[3] { "Blowjob", "quickshot", "!Cum" },
			new string[5] { "how quickly would you spurt your load if someone were to take your @cock all the way down their throat", "you'd cum in seconds if you got a blowjob, and that's no fun for anyone", "you may be able to cum from just a single lick across the head", "if your @cock ever ended up in someone's throat, you'd cum before they could even close their lips around your dick", "I think it's better for you to be a spectator, your @cock couldn't handle that much stimulation" },
			new string[3] { "quickshot", "Vanilla", "!Cum" },
			new string[3] { "I'm sorry but with your stamina it seems too unrealistic to even fantasize about having sex", "you really should fix your stamina before you try to get laid", "see how they aren't cumming instantly when they put it in, you should learn from that" },
			new string[3] { "quickshot", "Anal", "Femboy" },
			new string[3] { "if you just use your ass it's not that big of a deal that your @cock is so weak", "anal may be just the solution for someone with a @cock like yours", "you really do want to take his place don't you? then your premature dick won't get in the way anymore" },
			new string[3] { "Boobs", "Nude", "humiliation" },
			new string[2] { "you don't actually think that you deserve to see those tits right?", "nipples are too much for you" },
			new string[4] { "Nude", "censorship", "@!censor", "@!noCensors" },
			new string[4] { "this is too much nudity, I'm going to turn on the censors for a bit CENSORON", "sorry but there is way too much exposure CENSORON", "you shouldn't get used to too much nudity CENSORON", "there is such a thing as too much of a good thing CENSORON" },
			new string[3] { "gay", "!SPH", "Cock" },
			new string[4] { "you love cock don't you?", "just look at that delicious cock", "a cock like that would rock your world", "just look at the veins on that dick" },
			new string[1] { "MILF" },
			new string[2] { "you really are into MILF's aren't you?", "do you have some mommy issues to sort out or something?" },
			new string[2] { "Cuckold", "cuck" },
			new string[5] { "I wonder in who's shoes you're imagining yourself to be", "god, I hope you don't think you've got any chance against someone like that", "don't try to stop others from having fun, even if after a while they tend to forget all about you", "maybe there's a nice closet you could peek in from", "there may just be enough space under the bed for you to enjoy yourself as well" },
			new string[3] { "Cuckold", "cuck", "Girl(s)" },
			new string[7] { "hey if you get cucked that at least means you've got a girlfriend, not that you'll keep her long", "girls have the right to choose their own partner, too bad no one is picking you", "are you sure you should let her go? rather, are you sure she'll come back?", "look at her, is she doing this just for you?", "I'm sure she'll come back to you, right?", "you should be grateful to her, she's doing this for you", "does she make an expression like that when you're with her?" },
			new string[1] { "Hypnosis" },
			new string[4] { "are you starting to feel a bit loopy?", "don't stare too hard or you won't be able to stop", "you absolutely love hypnosis don't you?", "stare too deep and you'll never come back up" },
			new string[1] { "Humiliation" },
			new string[2] { "just how much would you be willing to give up to be in their place?", "I'll have you experience these fantasies for yourself one day" },
			new string[1] { "Horny" },
			new string[3] { "you don't look too different from them right now", "you're just as needy as them", "those eyes remind me of someone but I can't quite put my finger on it" },
			new string[1] { "Armpits" },
			new string[5] { "you look so needy, it's not because of their armpits is it?", "you and those pits deserve each other", "who could have expected that you'd focus on armpits", "just look at those smooth curves", "now that I know people like you are into this I'll stop wearing short sleeved shirts" },
			new string[1] { "Leash" },
			new string[3] { "just one tug and they have to follow their owner", "a leash is such a pretty tool", "few things symbolize our relationship as well as a leash and collar" }
		};
	}
}
