using OpenEdge.helper;

namespace OpenEdge.vocab;

internal class Tease : BaseVocab
{
	public Tease(Voc voc)
		: base(voc)
	{
		normal.AddRange(new string[44]
		{
			"drool for me", "spit on your hand", "you can take more of this right?", "show me just how devoted you are", "everything should be nice and slippery", "I want your @cock covered in spit", "as long as you keep doing as you're told I won't be too cruel, to my standards at least", "many people would give a limb to serve me, many more would give a limb to leave", "now that I've got you, I'm never going to let you leave", "I tend to get rather possessive of my toys",
			"you're thinking way too hard, just let me mold you", "I'm sure that you'll both hate and love this at the same time", "it may not have fully sunken in yet just how binding my words are to you now, don't worry, I'll show you", "it really was a one in a thousand that we would meet, you don't know if that was good or bad luck", "when we have these sessions I expect you to be nude", "I don't want you to wear anything", "once I'm done with you you're going to hate edging, but you'll still return to it again and again", "I'll remind you of your place as many times as I deem necessary", "normally I like to think that I'm kind to the people around me, but with you I don't feel that need at all", "I can finally show off my more sadistic desires when I'm with you",
			"when we're together you can finally let go of how you're expected to behave in society", "show me all of you", "I want to see you in your most shameful form", "I love how much power I hold over you", "at some point you won't even be able to differentiate between pleasure and pain", "I can break you whenever I want, that I don't is only because I'm such a kind @missTitle", "in some far-off corner of your mind you're still trying to resist, don't worry, I'll stamp that feeling out in no time", "do your best to ignore the ache", "you belong to me now, that means that no one would complain even if I edged you for weeks on end", "isn't it just the natural order of things that you ended up beneath my heel?",
			"while you only have to show up once every three days I don't mind if you show up more often than that", "it takes a lot of confidence to come out as a sub, way more than it takes to be a dom", "your secret of being a submissive little pervert is safe with me, although you probably can't hide it very well", "we both need each other to do our part, so I'll be as strict as I can and you should suffer in silence", "while some dommes won't let you speak unless specifically commanded to, I quite enjoy hearing my effect on you", "maybe if you beg hard enough I'll make it easier", "don't hold your voice back, I want to hear you moan", "moan for me", "let me hear what I do to you", "let me hear your voice",
			"moan louder @subTitle", "what will you sound like a week from now, I can't wait to find out", "there are many things way beyond edging that I can do to you", "it's so much fun to watch you slowly break apart as you realize how fucked you are"
		});
		degrading.AddRange(new string[7] { "you are nothing without me", "if you had me, you probably wouldn't even know what to do with me", "there will be a moment where you realize just how fucked you are", "it's not about what you want anymore", "you will do as I say", "obey, @subTitle", "I love this feeling of superiority" });
		sph.AddRange(new string[2] { "I don't think I'm ever going to get over the size of your @cock", "did you ever think you had a real chance with me, packing a cock like that" });
		chastity.AddRange(new string[5] { "a locked cock is a good cock", "do you remember when you owned your @cock, me neither", "don't you regret letting me control the key to your cage?", "you'd better obey, I own you now", "control the dick and you control the guy" });
		quickShot.AddRange(new string[6] { "make sure you don't shoot your load too soon, I know how hard that is for you", "you won't be able to pleasure anyone if you can't last in bed", "you're just a pathetic quickshot", "don't cum unless I say so! I know that's difficult for you", "don't cum early like you do so often", "premature ejaculation is a real problem, but I'm sure you'll learn to deal with it" });
		virgin.AddRange(new string[7] { "it doesn't surprise me that you're a virgin", "you'll never touch a woman", "it makes sense to me that you have never touched a woman", "why would you even admit to being a virgin?", "I'll make sure to ridicule you, with every embarrassing truth you admit to", "so you're a virgin, I never would have guessed such a truly shocking development", "I love that you trust me enough to tell me you're a virgin, most people take things like that to their grave" });
		cuck.AddRange(new string[3] { "you being a cuck is just the natural order of things", "I could really use a good fuck... it's too bad you're pretty much useless in that department", "if you get too deep into cuckolding, you'll come to hate your own fetishes" });
		petPlay.AddRange(new string[3] { "as long as you're a pet, you can do no wrong", "being my little @pup is safe and comforting", "as my @pup you won't have any worries, you'll just get to feel good" });
		humiliation.AddRange(new string[18]
		{
			"it's almost sad how easy it is to control you", "as long as I'm mean to you, you'll do whatever I want", "I'm certain that you'll obey, sometimes you just need a bit of a push", "do you truly believe you're worthy of my attention?", "you ought to thank me for even gracing you with my presence", "god you disgust me", "if only you weren't such a loser, maybe you wouldn't be here", "you're such a pervert", "don't expect your sex life to ever get better than this, loser", "this is it isn't it? this is your sex life now...",
			"watching a @man masturbate can be really sexy, but this is just pathetic", "this is the only way you can get off, isn't it? that's so pathetic", "you're lucky I even let you touch that disgusting @cock", "someday I'm going to throw a party and make you do this in front of all my friends", "I would love to humiliate you in a public place", "you'll never be good enough for someone like me and you know it", "you're such a loser", "does it hurt yet? no? let's fix that"
		});
		cei.AddRange(new string[12]
		{
			"I can't wait to make you eat your own cum again", "keep going my little cum slut", "let's make a big creamy load, you might just have to eat it", "I bet you can almost taste that cum already, disgusting", "are you getting used to the taste of cum yet?", "go ahead, have a taste of that sweet sticky precum", "scoop up any precum and rub it on your lips, don't lick it off", "smear some precum right under your nose", "good @boys eat their cum", "if you are leaking precum, lick it for me",
			"maybe I'll let you cum just to see you eat it, don't get your hopes up though", "let's fill up those balls with lots of cum, I might make you swallow it"
		});
		feet.AddRange(new string[0]);
		gay.AddRange(new string[0]);
		sissy.AddRange(new string[6] { "you're such a cute sissy for me", "I really should make you walk around in panties like a good sissy", "you're such a pathetic little sissy", "I really want to make you dress up", "cute little sissy's belong in cute little dresses", "I want you to apply makeup, just so I can see it run down your cheeks" });
		kneeling.AddRange(new string[5] { "are your knees starting to hurt yet?", "you belong on your knees, ready to serve", "knees together @subTitle", "keep your back straight @subTitle", "this is a proper pose for a @man like you" });
		longSinceOrgasm.AddRange(new string[10] { "your dick is almost like a broken faucet, it just keeps dripping precum", "it's cute how desperate for release you are", "we've almost reached your limit haven't we?", "that look in your eyes is almost primal, like there is a hunger deep inside you", "denial after denial, there are cracks forming in the mask you're wearing", "how much more can you take before it all becomes overwhelming", "every stroke and every edge is pushing you further down a hole that you can't crawl out of", "a humanitarian aid group would help you if you told them about our little sessions", "what started out as innocent make-believe has turned into a chain around your neck", "do you want to touch your dick? it's only going to make the ache worse you know?" });
		shortSinceOrgasm.AddRange(new string[4] { "you came just a little while ago, why do you already look this pathetic?", "you can hold it back a little longer for me right?", "I don't believe you've got much of a shot for reaching orgasm today", "you've got a long road ahead of you if you're acting like this after just a little bit of denial" });
		censoredView.AddRange(new string[19]
		{
			"you're getting denied even the porn you love", "blurs and bars are good for you", "act like a good sub and you'll be rewarded with less intense censors", "can you believe some subs get off to censors?", "you're going to associate pleasure with the censors if we keep this up", "I wonder how long it will take for the censors to become more appealing than the porn it's hiding", "you really are a freak for letting me do this to you", "god you're pathetic for being into this shit", "you probably thought that the denial of your cock would be the end of it", "you don't deserve to see nudity",
			"maybe I should keep this up permanently", "I'm sure you're not missing much, I mean, you've seen those pictures before", "why do you look hornier now than before the images got censored?", "do you really believe that you deserve the uncensored versions?", "if you were a better sub I wouldn't have to bully you like this", "the censors will get worse if you don't do exactly as I say", "I think this may be your lowest point so far, you can barely even see anything and you're getting hotter and hotter", "you may just forget what your favorite porn looks like if we keep this up", "if you don't act like the perfect plaything, I'll take even more of your sight"
		});
		moodLow.AddRange(new string[12]
		{
			"you really should be trying harder, I'm not even making you do anything difficult", "I'm starting to get annoyed, @subTitle", "you're really going to want to keep me happy or you'll suffer the consequences", "if you keep pushing my buttons like this, you're going to regret it", "do you even want to cum at some point in the future?", "keep going as you are now and I'll drag you into hell", "you don't want to disappoint me anymore than you already have right?", "obedience doesn't come easy to you does it? don't worry, I'll beat it into you", "many others can take your place, so you'd better start behaving", "some people like to act like brats, some people enjoy breaking those brats",
			"you're going to hate this if you don't start putting my needs before your own", "how clear do I have to be, you exist to serve, @subTitle"
		});
		moodHigh.AddRange(new string[8] { "you're doing good @subTitle", "you can't go against me anymore can you?", "you're acting so docile and submissive for me", "you look amazing like this", "I should just order you to go around the house naked", "I love your cute ass", "suffer more for your @missTitle", "if you keep acting this obedient, I may just have to reward you" });
		plug.AddRange(new string[7] { "squeeze down on your plug for me", "make your tight little hole clamp around your plug", "I really should just have you wearing a plug non-stop", "your ass belongs to me, and that plug is there to remind you", "I love training your ass like this", "we should increase the size of that plug of yours", "you love being plugged up don't you?" });
		ballsBound.AddRange(new string[3] { "your balls must feel extra full now that they're tied up like that", "give those bound balls a little tug", "binding your balls makes everything so much more sensitive" });
		clamp.AddRange(new string[5] { "are your nipples starting to hurt yet?", "I love how sensitive your nipples are", "you look gorgeous with those clamps on your nipples", "is the pressure of the clamps becoming too much for you? does it help that I'm reminding you of them?", "give those clamps a little twist for me" });
		findom.AddRange(new string[1] { "it's only fair that I take from you, you're so weak after all" });
		collar.AddRange(new string[4] { "you look beautiful with my collar around your neck", "I love how submissive you look with that collar on", "that collar serves as a reminder that you belong to me", "it's so soothing to feel that collar around your neck, isn't it" });
	}
}
